version: '3'
services:
  crud-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/finestmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 8080:8080
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_DB: finestmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  front-app:
    build:
      context: .
      dockerfile: src/main/frontend/crud-app-front/Dockerfile
    depends_on:
      - crud-app
    ports:
      - 4200:80
